version: '2'

networks:
  servicenet:
    driver: bridge

services:
  eureka-service:
    image: transport-service/eureka-service
    ports:
            - "8761:8761"
    networks:
            - servicenet

  connote-service:
     image: transport-service/connote-service

     networks:
             - servicenet
     depends_on:
             - eureka-service

  spring-boot-admin:
     image: transport-service/spring-boot-admin
     ports:
             - "8099:8080"
     networks:
             - servicenet
     depends_on:
             - eureka-service

  address-service:
       image: transport-service/address-service

       networks:
               - servicenet
       depends_on:
               - eureka-service

  customer-service:
         image: transport-service/customer-service

         networks:
                 - servicenet
         depends_on:
                 - eureka-service

  booking-service:
         image: transport-service/booking-service
         ports:
                - "8082:8082"

         networks:
                 - servicenet
         depends_on:
                 - eureka-service
  transport-api-gateway:
         image: transport-service/transport-api-gateway
         ports:
                 - "8081:8080"
         networks:
                 - servicenet
         depends_on:
                 - eureka-service

  zipkin-service:
         image: transport-service/zipkin-service
         ports:
                - "9411:9411"
         networks:
                - servicenet
         depends_on:
                - eureka-service

  hystrix-turbine-service:
         image: transport-service/hystrix-turbine-dashboard
         ports:
                - "8989:8989"
                - "8988:8080"
                - "8987:8081"
         networks:
                - servicenet
         depends_on:
                - eureka-service
  etcd:
        image: elcolio/etcd
        command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
        ports:
          - "2379:2379"
        networks:
          - servicenet
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - servicenet