version: '2'

networks:
  servicenet:
    driver: bridge

services:
  eureka-server:
    image: transport-service/eureka-server
    ports:
            - "8761:8761"
    networks:
            - servicenet

  connote-service:
     image: transport-service/connote-service

     networks:
             - servicenet
     depends_on:
             - eureka-server

  spring-boot-admin:
     image: transport-service/spring-boot-admin
     ports:
             - "8099:8080"
     networks:
             - servicenet
     depends_on:
             - eureka-server

  address-service:
       image: transport-service/address-service

       networks:
               - servicenet
       depends_on:
               - eureka-server

  customer-service:
         image: transport-service/customer-service

         networks:
                 - servicenet
         depends_on:
                 - eureka-server

  booking-service:
         image: transport-service/booking-service

         networks:
                 - servicenet
         depends_on:
                 - eureka-server
  transport-api-gateway:
         image: transport-service/transport-api-gateway
         ports:
                 - "8081:8080"
         networks:
                 - servicenet
         depends_on:
                 - eureka-server